name: AWS-ECR
on: 
  pull_request:
    types: [closed]
jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: kciter/aws-ecr-action@v3
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: kapsule/kapsule-ui
        region: eu-central-1
        tags: latest,${{ github.sha }}
        create_repo: true
        set_repo_policy: true
        repo_policy_file: repo-policy.json

